credentials:
  usernames:
    nowadays_studio:
      name: "Nowadays Studio"
      password: "$2b$12$Wq2g68LgkmgTUnx/BYYB5.HbHIvMBcqBesjlZPBPAGHcYnfqCTxXa"  # reemplaza con contrase√±a cifrada
    botanerolimon:
      name: "Botanero Limon"
      password: "abc"
    nuelengiere: 
      name: "Nue Lengiere"
      password: "123"

cookie:
  name: "dashboard_cookie"
  key: "random_key_string"
  expiry_days: 30
